// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using corridaFormula1.Data;

namespace corridaFormula1.Migrations
{
    [DbContext(typeof(corridaFormula1Context))]
    partial class corridaFormula1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("corridaFormula1.Models.corrida", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("equipe")
                        .HasColumnType("TEXT");

                    b.Property<string>("piloto")
                        .HasColumnType("TEXT");

                    b.Property<string>("posicao")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("corrida");
                });
#pragma warning restore 612, 618
        }
    }
}
